site_name: RedisTimeSeries - Time-Series data structure for Redis
site_url: http://redistimeseries.io
repo_url: https://github.com/RedisTimeSeries/RedisTimeSeries
repo_name: RedisTimeSeries/RedisTimeSeries

google_analytics:
  - 'UA-92003007-1'
  - 'auto'

extra_javascript:
  - gtm.js

use_directory_urls: true

theme:
  name: 'material'
  language: 'en'
  logo: 'images/logo_small.png'
  favicon: 'images/favicon.png'
  palette:
    primary: 'indigo'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false

nav:
  - 'Quickstart': index.md
  - 'Commands': commands.md
  - 'Configuration': configuration.md
  - 'Development': development.md
  - 'Clients': clients.md
  - Reference:
    - 'Out-of-order/backfilled ingestion performance considerations': 'out-of-order_performance_considerations.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - toc:
      permalink: True
      toc_depth: 3

plugins:
  - search
  - modules-template:
      modules:
        - name: 'Search'
          link: '/redisearch'

        - name: 'Bloom'
          link: '/redisbloom'

        - name: 'Graph'
          link: '/redisgraph'

        - name: 'JSON'
          link: '/redisjson'

        - name: 'AI'
          link: '/redisai'

        - name: 'Gears'
          link: '/redisgears'
  - versions-menu
