site_name: RedisTimeSeries - Time-Series data structure for Redis
site_url: http://redistimeseries.io
repo_url: https://github.com/RedisTimeSeries/RedisTimeSeries
repo_name: RedisTimeSeries/RedisTimeSeries

google_analytics:
  - 'UA-92003007-1'
  - 'auto'

use_directory_urls: true

theme:
  name: 'material'
  language: 'en'
  logo: 'images/logo_small.png'
  favicon: 'images/favicon.png'
  palette:
    primary: 'indigo'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false

pages:
    - 'Quickstart': index.md
    - 'Commands': commands.md
    - 'Configuration': configuration.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - toc:
      permalink: True
